DROP SCHEMA IF EXISTS RES_GEN;
CREATE SCHEMA IF NOT EXISTS RES_GEN DEFAULT CHARACTER SET UTF8MB4;
SHOW WARNINGS;

USE RES_GEN;

DROP TABLE IF EXISTS GRAFOS;
CREATE TABLE GRAFOS(
  GRF_ID INT NOT NULL AUTO_INCREMENT,
  GRF_N INT NOT NULL,
  GRF_M INT NOT NULL,
  GRF_NOME VARCHAR(255) NULL,
  GRF_VERTICES LONGBLOB NULL,
  GRF_ADJS LONGBLOB NULL,
  GRF_ORIGEM INT NOT NULL DEFAULT 0,
  PRIMARY KEY (GRF_ID))
ENGINE = InnoDB;
SHOW WARNINGS;

DROP TABLE IF EXISTS REQUISITOS;
CREATE TABLE REQUISITOS(
  REQ_ID INT NOT NULL AUTO_INCREMENT,
  REQ_GRAFO INT NOT NULL,
  REQ_CONST INT NULL,
  REQ_REQS LONGBLOB NULL,
  REQ_ORIGEM INT NOT NULL DEFAULT 0,
  PRIMARY KEY (REQ_ID),  
  CONSTRAINT REQ_GRAFO_FK FOREIGN KEY (REQ_GRAFO) REFERENCES GRAFOS(GRF_ID) ON DELETE CASCADE ON UPDATE CASCADE
)ENGINE = InnoDB;
SHOW WARNINGS;

DROP TABLE IF EXISTS TESTES;
CREATE TABLE TESTES (
  TST_ID INT NOT NULL AUTO_INCREMENT,
  TST_GRAFO INT NOT NULL,
  TST_REQS INT NOT NULL,
  TST_CP_MIN INT DEFAULT 0,
  TST_CP_MAX INT DEFAULT 0,
  TST_CP_SMELHORA INT DEFAULT 0,
  TST_GRUPO INT DEFAULT 0,
  TST_COMENTARIO TEXT DEFAULT NULL,  
  TST_COMP_TAM INT NULL,
  TST_COMP_TEMPO BIGINT NULL,
  TST_COMP_SOL LONGTEXT NULL,
  TST_EXATO_TAM INT DEFAULT NULL,
  TST_EXATO_TEMPO BIGINT DEFAULT NULL,
  TST_EXATO_SOL LONGTEXT DEFAULT NULL,
  TST_PROCESSADORES INT DEFAULT 0,
  PRIMARY KEY (TST_ID),
  CONSTRAINT TST_GRAFO_FK FOREIGN KEY (TST_GRAFO) REFERENCES GRAFOS(GRF_ID) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT TST_REQ_FK FOREIGN KEY (TST_REQS) REFERENCES REQUISITOS (REQ_ID) ON DELETE CASCADE ON UPDATE CASCADE
)ENGINE = InnoDB;
SHOW WARNINGS;

DROP TABLE IF EXISTS RESULTADOS;
CREATE TABLE RESULTADOS (
  RES_ID INT NOT NULL AUTO_INCREMENT,
  RES_TESTE INT NOT NULL,
  RES_TERM_OK BOOL DEFAULT 1,
  RES_TAM INT NOT NULL,
  RES_TEMPO BIGINT NOT NULL,
  RES_GERACOES INT NOT NULL,
  RES_MAXSEMMUDANCA INT NOT NULL,
  RES_SOL LONGTEXT NOT NULL,
  PRIMARY KEY (RES_ID),
  CONSTRAINT RES_TST_FK FOREIGN KEY (RES_TESTE) REFERENCES TESTES (TST_ID) ON DELETE CASCADE ON UPDATE CASCADE
)ENGINE = InnoDB;
SHOW WARNINGS;

DROP TABLE IF EXISTS LOG_MELHORIAS;
CREATE TABLE LOG_MELHORIAS (
	LGM_ID INT NOT NULL AUTO_INCREMENT,
	LGM_RES INT NOT NULL,	
	LGM_PAI1_TAM INT NOT NULL,
	LGM_PAI2_TAM INT NOT NULL,	
	LGM_NOVO_TAM INT NOT NULL,
	LGM_ANT_TAM INT NOT NULL,	
	LGM_OPERACAO INT NOT NULL,	
	LGM_GERACAO INT NOT NULL,
	LGM_SEMMELHORIA INT NOT NULL,
	LGM_AMPLITUDE INT NOT NULL,
	PRIMARY KEY (LGM_ID),
	CONSTRAINT LGM_RES_FK FOREIGN KEY (LGM_RES) REFERENCES RESULTADOS (RES_ID) ON DELETE CASCADE ON UPDATE CASCADE	
) ENGINE = InnoDB;
SHOW WARNINGS;

DROP TABLE IF EXISTS LOG_OPERADORES;
CREATE TABLE LOG_OPERADORES (
	LGO_ID INT NOT NULL AUTO_INCREMENT,
	LGO_RES INT NOT NULL,	
	LGO_OP INT NOT NULL,
	LGO_EXECS BIGINT NOT NULL,
	LGO_AVG_EXEC DECIMAL(65,30) NOT NULL,
	LGO_AVG_OTM DECIMAL(65,30) NOT NULL,
	PRIMARY KEY (LGO_ID),
	CONSTRAINT LGO_RES_FK FOREIGN KEY (LGO_RES) REFERENCES RESULTADOS (RES_ID) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = InnoDB;
SHOW WARNINGS;

DROP TABLE IF EXISTS LOG_GERACOES;
CREATE TABLE LOG_GERACOES (
	LGG_ID INT NOT NULL AUTO_INCREMENT,
	LGG_RES INT NOT NULL,
	LGG_ITERACAO INT NOT NULL,
	LGG_OPERADOR INT NOT NULL,
	LGG_TAM_FILHO_INI INT NOT NULL,
	LGG_TAM_FILHO_OTM INT NOT NULL,
	LGG_MSECS_OP INT NOT NULL,
	LGG_MSECS_OTM INT NOT NULL,
	LGG_AMPLITUDE INT NOT NULL,
	LGG_MUTACAO INT NOT NULL,
	PRIMARY KEY (LGG_ID),
	CONSTRAINT LGG_RES_FK FOREIGN KEY (LGG_RES) REFERENCES RESULTADOS (RES_ID) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = InnoDB;
SHOW WARNINGS;
